project_root: '%WORKING_DIR%/vendor/doctrine'
templates_dir: '%WORKING_DIR%/demo/demo1/templates'
cache_dir: '%WORKING_DIR%/demo/demo1/__cache'
output_dir: "%WORKING_DIR%/demo/demo1/docs"
output_dir_base_url: "/demo/demo1/docs"
check_file_in_git_before_creating_doc: false
language_handlers:
  php:
    class: \BumbleDocGen\LanguageHandler\Php\PhpHandler
    settings:
      file_source_base_url: '#'
source_locators:
  - class: \BumbleDocGen\Core\Parser\SourceLocator\RecursiveDirectoriesSourceLocator
    arguments:
      directories:
        - "%project_root%"