language_handlers:
  php:
    class: \BumbleDocGen\LanguageHandler\Php\PhpHandler
    settings:
      class_filter:
        class: \BumbleDocGen\Core\Parser\FilterCondition\CommonFilterCondition\TrueCondition

      class_constant_filter:
        class: \BumbleDocGen\LanguageHandler\Php\Parser\FilterCondition\ClassConstantFilterCondition\VisibilityCondition
        arguments:
          - public
          - protected

      method_filter:
        class: \BumbleDocGen\LanguageHandler\Php\Parser\FilterCondition\MethodFilterCondition\IsPublicCondition

      property_filter:
        class: \BumbleDocGen\Core\Parser\FilterCondition\ConditionGroup
        arguments:
          - and
          - class: \BumbleDocGen\LanguageHandler\Php\Parser\FilterCondition\PropertyFilterCondition\IsPublicCondition
          - class: \BumbleDocGen\LanguageHandler\Php\Parser\FilterCondition\PropertyFilterCondition\OnlyFromCurrentClassCondition

      doc_renderers:
        - class: \BumbleDocGen\LanguageHandler\Php\Renderer\EntityDocRenderer\PhpClassToMd\PhpClassToMdDocRenderer

      custom_twig_functions:
        - class: \BumbleDocGen\LanguageHandler\Php\Renderer\Twig\Function\DrawClassMap
        - class: \BumbleDocGen\LanguageHandler\Php\Renderer\Twig\Function\GetClassMethodsBodyCode

      custom_twig_filters:

      file_source_base_url: null

      use_composer_autoload: true # whether to use composer to load the class map or not
      composer_config_file: "%project_root%/composer.json"
      composer_installed_file: "%project_root%/vendor/composer/installed.json"
      psr4_map: # same as in composer
plugins:
  - class: \BumbleDocGen\LanguageHandler\Php\Plugin\CorePlugin\BasePhpStubber\BasePhpStubberPlugin
  - class: \BumbleDocGen\LanguageHandler\Php\Plugin\CorePlugin\BasePhpStubber\PhpDocumentorStubberPlugin
  - class: \BumbleDocGen\LanguageHandler\Php\Plugin\CorePlugin\ComposerPackagesStubber\StubberPlugin